language: go
go_import_path: github.com/ng-vu/ujson
go:
- 1.11.x
- 1.12.x
script:
- export PATH=$PATH:$HOME/gopath/bin
- export GORACE="halt_on_error=1"
- env GO111MODULE=on go install ./...
- env GO111MODULE=on go test -v -race ./...
